require 'test/unit'
require_relative '../lib/silva'
require_relative 'test_data'
require_relative 'test_location'
require_relative 'test_wgs84'
require_relative 'test_en'
require_relative 'test_osgb36'
require_relative 'test_gridref'
